name: HOLOPHONIX glTF Export CI

on:
  push:
    branches: [main, develop]
    tags: ["v*"]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Extension Package
        run: |
          mkdir -p dist
          cp -r src/HOLOPHONIX_gltf_export dist/
          cp src/HOLOPHONIX_gltf_export.rb dist/
          echo "Package created successfully!"
          find dist -type f | wc -l

      # Skip artifact upload for local testing with act
      # The following steps will only work on GitHub, not locally
      - name: Prepare for artifact upload
        run: echo "Ready to upload artifact (this would fail locally with act)"

      - name: Archive Extension Package
        if: github.event_name != 'act'
        uses: actions/upload-artifact@v3
        with:
          name: holophonix-gltf-export
          path: dist/
          retention-days: 7

  # This job is used for GitHub only, not for local testing
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3

      - name: Download Extension Package
        uses: actions/download-artifact@v3
        with:
          name: holophonix-gltf-export
          path: dist

      - name: Create ZIP Archive
        run: |
          cd dist
          zip -r ../HOLOPHONIX_gltf_export_${{ github.ref_name }}.zip .
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: HOLOPHONIX_gltf_export_${{ github.ref_name }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
