name: HOLOPHONIX glTF Export CI

# Add permissions section at the top level
permissions:
  contents: write # This gives permission to create releases

on:
  push:
    branches: [main, develop]
    tags: ["v*"]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Extension Package
        run: |
          mkdir -p dist
          cp -r src/HOLOPHONIX_gltf_export dist/
          cp src/HOLOPHONIX_gltf_export.rb dist/
          echo "Package created successfully!"
          find dist -type f | wc -l

      - name: Create ZIP Archive
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd dist
          zip -r ../HOLOPHONIX_gltf_export.zip .
          cd ..

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: HOLOPHONIX_gltf_export.zip
          draft: false
          prerelease: false
          generate_release_notes: true
